# -*- coding: utf-8 -*-

# XXX: generated by `nikola default_config`.
from default_conf import *


# XXX: inherits from origin_conf
from origin_conf import (
    BLOG_AUTHOR,
    BLOG_TITLE,
    SITE_URL,
    BLOG_EMAIL,
    BLOG_DESCRIPTION,
    DEFAULT_LANG,
    TRANSLATIONS,
    TRANSLATIONS_PATTERN,
    NAVIGATION_LINKS,
    THEME,
    TIMEZONE,
    SHOW_UNTRANSLATED_POSTS,
    DEPLOY_COMMANDS,
    # DON'T KNOW WHY, but used.
    GENERATE_RSS,
    COPY_SOURCES,
)

# XXX: override default_config values
GITHUB_SOURCE_BRANCH = 'source'
COMMENT_SYSTEM = ""
COMMENT_SYSTEM_ID = ""

FILE_METADATA_UNSLUGIFY_TITLES = True


# XXX: Use `misaka` compiler for Markdown.
COMPILERS["misaka"] = COMPILERS.pop("markdown")
# XXX: Patched `misaka` with CodeHighlighter.

